language: cpp
dist: trusty
sudo: false

notifications:
    email: false

cache:
    - apt
    - ccache

addons:
    apt:
        packages:
            - qt5-default
            - zlib1g-dev
            - libosmesa6-dev
            - libssl-dev
            - libqwt-dev
            - libfreetype6-dev
            - libftgl-dev

env:
    global:
        - OSMESA_DIR=/usr
        - OMP_NUM_THREADS=4

before_install:
    - mkdir ../build
    - cd ../build

script:
    - cmake ../workbench/src
    - make -j 4
    - ctest
